In [3]:
import numpy as np

In [11]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [15]:
def sigmoid_derivative(x):
    return x*(1-x)

In [48]:
training_inputs = np.array([[0,0,1],
                           [1,1,1],
                           [1,0,1],
                           [0,1,1],
                           [1,0,0]])
training_outputs = np.array([[0,1,1,0,1]]).T

In [49]:
np.random.seed(1)

In [50]:
synaptic_weights = 2*np.random.random((3,1))-1

In [51]:
print("RAndom starting synaptic weights are: ")
print(synaptic_weights)

RAndom starting synaptic weights are: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [52]:
for i in range(200000):
    input_layer = training_inputs
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))
    error = training_outputs - outputs
    adjustments = error*sigmoid_derivative(outputs)
    synaptic_weights+=np.dot(input_layer.T, adjustments)

In [53]:
print("Synaptic weights after ttaining:")
print(synaptic_weights)

Synaptic weights after ttaining:
[[12.70631872]
 [-0.20392516]
 [-6.14947977]]


In [54]:
print("outputs after training: ")
print(outputs)

outputs after training: 
[[0.00213005]
 [0.99826136]
 [0.99858164]
 [0.00173779]
 [0.99999697]]
